const ROLES = {
  ADMIN: 'ADMIN',
  PROPONENT: 'PROPONENT',
  SCRUTINY: 'SCRUTINY',
  MOM: 'MOM',
};

const APP_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_SCRUTINY: 'UNDER_SCRUTINY',
  ESSENTIAL_DOC_SOUGHT: 'ESSENTIAL_DOC_SOUGHT',
  REFERRED: 'REFERRED',
  MOM_GENERATED: 'MOM_GENERATED',
  FINALIZED: 'FINALIZED',
};

const VALID_TRANSITIONS = {
  [APP_STATUS.DRAFT]: [APP_STATUS.SUBMITTED],
  [APP_STATUS.SUBMITTED]: [APP_STATUS.UNDER_SCRUTINY],
  [APP_STATUS.UNDER_SCRUTINY]: [APP_STATUS.ESSENTIAL_DOC_SOUGHT, APP_STATUS.REFERRED],
  [APP_STATUS.ESSENTIAL_DOC_SOUGHT]: [APP_STATUS.UNDER_SCRUTINY],
  [APP_STATUS.REFERRED]: [APP_STATUS.MOM_GENERATED],
  [APP_STATUS.MOM_GENERATED]: [APP_STATUS.FINALIZED],
  [APP_STATUS.FINALIZED]: [],
};

module.exports = {
  ROLES,
  APP_STATUS,
  VALID_TRANSITIONS,
};
